# nixpacks.toml

# Tentukan paket-paket sistem yang harus diinstal
[phases.setup]
nixPkgs = ["php82", "php82Extensions.pdo_mysql"]

# Tentukan perintah yang harus dijalankan saat build
[phases.build]
cmds = ["composer install --no-dev --optimize-autoloader"]

# Tentukan perintah untuk memulai server
[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"