[build]
builder = "nixpacks"
nixpacksPlan = """
pkgs = [
    "php82Extensions.pdo_mysql"
]
"""

[deploy]
startCommand = "php artisan serve --host=0.0.0.0 --port=$PORT"
healthcheckPath = "/"
healthcheckTimeout = 300